<a href="https://colab.research.google.com/github/Bhavya728/Bhavya-UCS420/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like: a) Addition of 2 in all the element b) Multiply 3 with all the elements c) Divide every element by 2

In [2]:
import numpy as np

a = np.array([0,1,2,3,4])

a = a+2
print(a)

[2 3 4 5 6]


In [ ]:
# Multiply 3 with all the elements

a = a*2
print(a)

[ 4  6  8 10 12]


In [ ]:
# Divide every element by 2

a = a/2
print(a)

[2. 3. 4. 5. 6.]



Q.2 Questions on Basic NumPy Array: a) Reverse the NumPy array: arr = np.array([1,2,3,6,4,5]) b) Find the most frequent value and their indice(s) in the following arrays: i. x = np.array([1,2,3,4,5,1,2,1,1,1]) ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
arr = np.array([1,2,3,6,4,5])
print(f"before reversing the array : ",arr)

arr1 = np.flip(arr)
print(f"after reversing the array : ",arr1)

before reversing the array :  [1 2 3 6 4 5]
after reversing the array :  [5 4 6 3 2 1]


In [3]:
y = np.array([1,1,1,2,3,4,2,4,3,3])

unique,counts = np.unique(y,return_counts=True)

most_frequent = np.where(counts==max(counts))
print(f"most frequent occuring element in the array is : ",unique[most_frequent])
print(f"indices where most frequent occuring element exist : ",np.where(y==unique[most_frequent][0]))

most frequent occuring element in the array is :  [1 3]
indices where most frequent occuring element exist :  (array([0, 1, 2]),)


In [4]:
x = np.array([1,2,3,4,5,1,2,1,1,1])

unique,counts = np.unique(x,return_counts=True)
most_frequent = np.where(counts==max(counts))
print(f"most frequent occuring element in the array is : ",unique[most_frequent])
print(f"indices where most frequent occuring element exist : ",np.where(x==unique[most_frequent]))

most frequent occuring element in the array is :  [1]
indices where most frequent occuring element exist :  (array([0, 5, 7, 8, 9]),)


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]),
 access elements using row and column indices as follows: a) Access 1st row,
  2nd column b) Access 3rd row, 1st column

In [ ]:

arr = np.array([[10,20,30],[40,50,60],[70,80,90]])

print(arr[0][1])
print(arr[2][0])

20
70


Q.4 Write program to create an 1-D NumPy array named <> with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute?

In [ ]:
x = np.linspace(10,100,25)
print(x)

print(f"dimension of this array is : ",x.ndim)
print(f"shape of this array is : ",x.shape)
print(f"total elements in this array is : ",np.size(x))
print(f"data type of elements in this array is : ",x.dtype)
print(f"total number of bytes in this array is : ",x.itemsize*x.size)
print()


print("printing transpose of this matrix : \n")

x_col = x.reshape(25,1)
print(x_col)

print(x_col.T)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
dimension of this array is :  1
shape of this array is :  (25,)
total elements in this array is :  25
data type of elements in this array is :  float64
total number of bytes in this array is :  200

printing transpose of this matrix : 

[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three columns and name it as resized_ ucs420_<your_name>>.

In [ ]:
ucs420_bhavya = [[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]]

print("mean of this array is:", np.mean(ucs420_bhavya))
print("median of this array is:", np.median(ucs420_bhavya))
print("maximum of this array is:", np.max(ucs420_bhavya))
print("minimum of this array is:", np.min(ucs420_bhavya))
print("unique elements in this array:", np.unique(ucs420_bhavya))

reshaped_ucs420_bhavya = np.reshape(ucs420_bhavya, (4, 3))
print("reshaped array:\n", reshaped_ucs420_bhavya)

resized_ucs420_bhavya= np.resize(ucs420_bhavya, (2, 3))
print("resized array:\n", resized_ucs420_bhavya)

mean of this array is: 43.333333333333336
median of this array is: 37.5
maximum of this array is: 90
minimum of this array is: 10
unique elements in this array: [10 15 20 30 35 40 50 60 70 80 90]
reshaped array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
resized array:
 [[10 20 30]
 [40 50 60]]
